timeout: 600s

options:
  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/worker-pool-high-cpu-8'

# Cache the testbase image in Container Registry to be reused by subsequent builds.
# The technique is described here:
# https://cloud.google.com/cloud-build/docs/speeding-up-builds#using_a_cached_docker_image
images: [
  'gcr.io/$PROJECT_ID/python_worker_sdk:latest',
  'gcr.io/$PROJECT_ID/python_worker_sdk:$BRANCH_NAME-$SHORT_SHA',
  'gcr.io/$PROJECT_ID/python_worker_sdk:$BRANCH_NAME-latest',
]

steps:
  # Try to pull the prior image from Container Registry.
  - id: 'pull-latest-image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/python_worker_sdk:latest || exit 0']
    waitFor: ['-']

  - id: 'pull-latest-branch-image'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/python_worker_sdk:$BRANCH_NAME-latest || exit 0']
    waitFor: ['-']

  # Build the image reusing as much of the cached image as possible.
  - id: 'build-image'
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/python_worker_sdk:latest',
        '-t',
        'gcr.io/$PROJECT_ID/python_worker_sdk:$BRANCH_NAME-$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/python_worker_sdk:$BRANCH_NAME-latest',
        '--cache-from',
        'gcr.io/$PROJECT_ID/python_worker_sdk:$BRANCH_NAME-latest',
        '--cache-from',
        'gcr.io/$PROJECT_ID/python_worker_sdk:latest',
        '--file=python/Dockerfile.build',
        '.',
      ]
    waitFor: ['pull-latest-image', 'pull-latest-branch-image']
