# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# rendered via <root>/template_renderer/scripts/render_ignore_templates.py

# Ignore everything
*

# inject dep exclusions here
# prove that the dockerignore file does nothing
# !python/.flake8
# !python/bin/**
# !python/Dockerfile.build
# !python/Dockerfile.build.dockerignore
# !python/Dockerfile.build.dockerignore.jinja2
# !python/poetry.lock
# !python/pyproject.toml
# !python/src/**
# !protobuf/**
