# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# rendered via <root>/template_renderer/scripts/render_ignore_templates.py

# Ignore everything
*

# inject dep exclusions here
#{{ ignore_excludes['python'] }}
