# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# rendered via <root>/bin/render_ignore_templates.py

# Ignore everything
*

# inject dep exclusions here
{{ ignore_excludes['anomaly_detection'] }}
{{ ignore_excludes['nike_auth_service'] }}
{{ ignore_excludes['observer_service'] }}
{{ ignore_excludes['scheduler_service'] }}
{{ ignore_excludes['shared_js'] }}
{{ ignore_excludes['template_renderer'] }}
{{ ignore_excludes['web_app'] }}