# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# rendered via <root>/bin/render_ignore_templates.py

# Ignore everything
*

# inject dep exclusions here
!python/.flake8
!python/bin/**
!python/Dockerfile.build
!python/Dockerfile.build.dockerignore
!python/Dockerfile.build.dockerignore.jinja2
!python/poetry.lock
!python/pyproject.toml
!python/src/**

!template_renderer/.ignore-excludes
!template_renderer/pyproject.toml
!template_renderer/scripts/**
